# Generated by Django 5.2.5 on 2025-08-31 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='s3_path',
        ),
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
    ]
