version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: gunicorn easydeploy.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery:
    environment:
      - GIT_PYTHON_REFRESH=quiet
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: celery -A easydeploy worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"

